services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logging:/api/API_MBART/logging
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             count: 1
             capabilities: [gpu]
